"""

Revision ID: 7b5f70ba4a72
Revises:
Create Date: 2025-04-27 03:58:14.100164

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b5f70ba4a72"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "text_analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "word_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("word", sa.String(length=255), nullable=False),
        sa.Column("tf", sa.Integer(), nullable=False),
        sa.Column("idf", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["text_analyses.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_results")
    op.drop_table("text_analyses")
    # ### end Alembic commands ###
