"""Add df and document_sources columns to word_results table

Revision ID: add_document_sources_columns
Revises: 7b5f70ba4a72
Create Date: 2024-05-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_document_sources_columns'
down_revision = '7b5f70ba4a72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_results', sa.Column('df', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('word_results', sa.Column('document_sources', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_results', 'document_sources')
    op.drop_column('word_results', 'df')
    # ### end Alembic commands ### 