"""

Revision ID: ed0064edf3fb
Revises: 7b5f70ba4a72
Create Date: 2025-04-27 17:41:26.204814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0064edf3fb'
down_revision = '7b5f70ba4a72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_results', sa.Column('df', sa.Integer(), nullable=False))
    op.add_column('word_results', sa.Column('document_sources', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word_results', 'document_sources')
    op.drop_column('word_results', 'df')
    # ### end Alembic commands ### 