name: Update Requirements

on:
  push:
    paths:
      - 'pyproject.toml'
    branches: [ main ]
  workflow_dispatch:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install Poetry Export Plugin
        run: |
          poetry self add poetry-plugin-export

      - name: Generate requirements files
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code requirements.txt || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Configure Git
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"

      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git add requirements.txt
          git commit -m "chore: Update requirements files from pyproject.toml [skip ci]"
          git push
